version: "3"
services:
  wppconnect-server:
    image: wppconnect-server:latest
    volumes:
      - ./tokens:/usr/src/wpp-server/tokens
      - ./userDataDir:/usr/src/wpp-server/userDataDir
    ports:
      - "21465:21465"
    working_dir: /usr/src/wpp-server
